sybinit.release_directory: USE_DEFAULT
sybinit.product: sqlsrv
sqlsrv.server_name: DBN
sqlsrv.sa_password: passw0rd
sqlsrv.new_config: yes
sqlsrv.do_add_server: yes
sqlsrv.network_protocol_list: tcp
sqlsrv.network_hostname_list: SRVDB
sqlsrv.network_port_list: 60NN
sqlsrv.application_type: USE_DEFAULT
sqlsrv.server_page_size: 2048
sqlsrv.force_buildmaster: yes
sqlsrv.master_device_physical_name: /sybase/data/master_DBN.dat
sqlsrv.master_device_size: 1024
sqlsrv.master_database_size: 128
sqlsrv.errorlog: USE_DEFAULT
sqlsrv.do_upgrade: no
sqlsrv.sybsystemprocs_device_physical_name: /sybase/data/sybsystemprocs_DBN.dat
sqlsrv.sybsystemprocs_device_size: 1024
sqlsrv.sybsystemprocs_database_size: 512
sqlsrv.sybsystemdb_device_physical_name: /sybase/data/systemdb_DBN.dat
sqlsrv.sybsystemdb_device_size: 1024
sqlsrv.sybsystemdb_database_size: 128
sqlsrv.tempdb_device_physical_name: /sybase/data/tempdb_DBN.dat
sqlsrv.tempdb_device_size: 4096
sqlsrv.tempdb_database_size: 2048
sqlsrv.default_backup_server: DB1_BS
sqlsrv.do_configure_pci: no
sqlsrv.do_optimize_config: no
